### ISSUE TITLE
ImportError: cannot import name urlConf  我不懂Python, 这个怎么解决啊?

### ISSUE THREAD

**Issue by SuJianWeii** [biandh/12306_flask#1]
Traceback (most recent call last):
  File "app.py", line 33, in <module>
    from GetTrainStatus import QueryTecket
  File "/home/jo/Github/12306_flask/inter/GetTrainStatus.py", line 13, in <module>
    from config import urlConf
ImportError: cannot import name urlConf

**Comment by biandh** [comment]
这个是基本的问题啦，看下config文件在不在
